### ISSUE TITLE
Action required: CircleCI v1.0 is EOL, this repo is impacted

### ISSUE THREAD

**Issue by ayatsynych** [Shopify/unity-buy-sdk#526] opened 2018-08-09 15:10 UTC
## This repository relies on CircleCI v1.0 which will be shut down on **Aug 31st**.

cc @mikkoh

**Comment by sleroux** [comment] 2018-10-01 15:29
Marking as dupe of https://github.com/Shopify/unity-buy-sdk/issues/508

**Closed by sleroux** 2018-10-01 15:29 UTC
